[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[phases.build]
cmds = ['echo "Build complete - using pre-built Flutter web"']

[start]
cmd = 'node server.js'
